spring:
  application:
    name: MobileAPI

  datasource:
    url: jdbc:postgresql://localhost:5433/argus_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: db7834

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true

